FROM boinc/server_makeproject:latest-b2d

COPY config.xml /root/project 
COPY test_work_gen.py /root/project/bin
COPY testAssim.py /root/project/bin
COPY testVal.py /root/project/bin
COPY testValComp.py /root/project/bin
